apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mariadb
  name: mariadb-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mariadb-root-password
          envFrom:
            - secretRef:
                name: mariadb-user-creds
          image: 'us.gcr.io/spinnaker-291817/mariadb:10.4'
          name: mariadb
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-volume-1
            - mountPath: /etc/mysql/conf.d
              name: mariadb-config-volume
      volumes:
        - emptyDir: {}
          name: mariadb-volume-1
        - configMap:
            items:
              - key: max_allowed_packet.cnf
                path: max_allowed_packet.cnf
            name: mariadb-config
          name: mariadb-config-volume
